import React, { useEffect, useState } from 'react';
import { confirmDecision, fetchDecisions, overrideDecision, processDecisionBatch } from '../services/api';

export default function RecoveryDecisions() {
  const [decisions, setDecisions] = useState([]);
  const [selectedId, setSelectedId] = useState('');
  const [filterActive, setFilterActive] = useState(false);
  const [decisionFilter, setDecisionFilter] = useState('ALL');
  const [toast, setToast] = useState('');

  const displayAction = (action) => action === 'CANCEL_MANDATE' ? 'CANCEL' : action;

  const backendAction = (action) => action === 'CANCEL' ? 'CANCEL_MANDATE' : action;

  const normalizeDecision = (item) => ({
    id: item.mandateId || item.id,
    probability: item.recoverabilityScore || 0,
    decision: displayAction(item.action || 'UNKNOWN'),
    decisionColor: item.action === 'CANCEL_MANDATE' ? 'bg-tertiary text-on-primary' : item.escalated ? 'bg-secondary text-on-primary' : 'bg-surface-tint text-on-primary',
    reason: item.decisionReasonCode || item.classification || 'No reason recorded',
    retryPlan: item.scheduledAt ? new Date(item.scheduledAt).toLocaleString() : 'N/A',
    customerName: item.mandateId || 'Backend Decision',
    customerTier: item.classification || 'Classification unavailable',
    customerId: item.mandateId || 'N/A',
    successRate: item.recoverabilityScore || 0,
    avgVolume: 'Backend data',
    historyDots: ['bg-primary', 'bg-outline-variant', 'bg-outline-variant'],
    reasoning: item.escalationReason || item.decisionReasonCode || 'Decision generated by the backend recovery agent.',
    nextAttempt: item.scheduledAt ? new Date(item.scheduledAt).toLocaleString() : 'N/A',
    attemptDetails: item.stopReason || item.escalationReason || 'No extra backend detail recorded.',
    breakdown: { base: item.recoverabilityScore || 0, history: 0, penalty: 0 },
  });

  useEffect(() => {
    fetchDecisions()
      .then((data) => {
        const normalized = data.map(normalizeDecision);
        setDecisions(normalized);
        setSelectedId(normalized[0]?.id || '');
      })
      .catch(() => showToast('Could not load backend decisions.'));
  }, []);

  // Find active decision item details
  const activeItem = decisions.find(d => d.id === selectedId) || decisions[0];

  // Apply filters
  const filteredDecisions = decisions.filter(item => {
    if (decisionFilter === 'ALL') return true;
    return item.decision === decisionFilter;
  });

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(''), 3000);
  };

  const handleConfirmPlan = async (id) => {
    try {
      await confirmDecision(id);
      showToast(`AI plan confirmed for ${id}.`);
    } catch {
      showToast(`Could not confirm AI plan for ${id}.`);
    }
  };

  const handleOverride = async (id) => {
    // Basic override selector toggle
    const newDecision = prompt(`Override Decision for ${id} (RETRY, CANCEL, ESCALATE, NOTIFY_CUSTOMER):`, activeItem.decision);
    if (newDecision && ['RETRY', 'CANCEL', 'ESCALATE', 'NOTIFY_CUSTOMER'].includes(newDecision.toUpperCase())) {
      const upper = newDecision.toUpperCase();
      const current = decisions.find((d) => d.id === id);
      try {
        const saved = await overrideDecision(id, {
          action: backendAction(upper),
          recoverabilityScore: current?.probability,
          classification: current?.customerTier,
          escalated: upper === 'ESCALATE',
          reason: 'Manual override from frontend',
        });
        const updated = normalizeDecision(saved);
        setDecisions(decisions.map((d) => d.id === id ? updated : d));
        showToast(`Decision updated to ${upper} for ${id}`);
      } catch {
        showToast(`Backend override failed for ${id}`);
      }
    }
  };

  return (
    <div className="p-container-padding flex-1 flex flex-col h-[calc(100vh-64px)] overflow-hidden relative">
      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 right-6 z-50 bg-inverse-surface text-inverse-on-surface px-6 py-3 rounded-lg shadow-level2 border border-outline-variant flex items-center gap-2 border-primary/20 animate-fade-in">
          <span className="material-symbols-outlined fill text-[#8a2be2]">auto_awesome</span>
          <span className="font-semibold">{toast}</span>
        </div>
      )}

      {/* Header Section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end mb-stack-lg gap-4 shrink-0">
        <div>
          <h2 className="font-headline-lg text-headline-lg text-on-surface">Recovery Decisions</h2>
          <p className="font-body-md text-body-md text-secondary mt-1">Review and manage AI-recommended recovery actions for failed mandates.</p>
        </div>
        <div className="flex gap-3 w-full sm:w-auto">
          <div className="relative">
            <button 
              onClick={() => setFilterActive(!filterActive)}
              className="px-4 py-2 border border-outline-variant rounded-lg font-label-md text-label-md text-on-surface hover:bg-surface-variant transition-colors flex items-center gap-2"
            >
              <span className="material-symbols-outlined text-[18px]">filter_list</span> Filter
            </button>

            {filterActive && (
              <div className="absolute right-0 mt-2 w-48 bg-surface rounded-lg border border-outline-variant shadow-level2 z-30 p-2">
                <button onClick={() => { setDecisionFilter('ALL'); setFilterActive(false); }} className="w-full text-left px-3 py-2 text-body-sm hover:bg-surface-container rounded">All Decisions</button>
                <button onClick={() => { setDecisionFilter('RETRY'); setFilterActive(false); }} className="w-full text-left px-3 py-2 text-body-sm hover:bg-surface-container rounded">Retry</button>
                <button onClick={() => { setDecisionFilter('CANCEL'); setFilterActive(false); }} className="w-full text-left px-3 py-2 text-body-sm hover:bg-surface-container rounded">Cancel</button>
                <button onClick={() => { setDecisionFilter('ESCALATE'); setFilterActive(false); }} className="w-full text-left px-3 py-2 text-body-sm hover:bg-surface-container rounded">Escalate</button>
                <button onClick={() => { setDecisionFilter('NOTIFY_CUSTOMER'); setFilterActive(false); }} className="w-full text-left px-3 py-2 text-body-sm hover:bg-surface-container rounded font-semibold text-[#6b21a8]">Notify Customer</button>
              </div>
            )}
          </div>

          <button 
            onClick={async () => {
              try {
                const results = await processDecisionBatch(filteredDecisions.map((item) => item.id));
                showToast(`Batch processed ${results.length} selected decisions.`);
              } catch {
                showToast('Backend batch processing failed.');
              }
            }}
            className="px-4 py-2 bg-primary rounded-lg font-label-md text-label-md text-on-primary hover:bg-on-primary-fixed-variant transition-colors shadow-sm whitespace-nowrap"
          >
            Process Batch ({filteredDecisions.length})
          </button>
        </div>
      </div>

      {/* Bento Layout for Content */}
      <div className="flex flex-col lg:flex-row gap-gutter flex-1 min-h-0">
        
        {/* Main Table Area */}
        <div className="flex-1 bg-surface-container-lowest rounded-xl border border-outline-variant/40 shadow-level1 flex flex-col overflow-hidden relative z-10 min-h-0">
          <div className="overflow-y-auto flex-1">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-outline-variant/40 bg-surface-container-low sticky top-0 z-10">
                  <th className="py-3 px-4 font-label-md text-label-md text-secondary whitespace-nowrap">Mandate ID</th>
                  <th className="py-3 px-4 font-label-md text-label-md text-secondary whitespace-nowrap">Probability</th>
                  <th className="py-3 px-4 font-label-md text-label-md text-secondary whitespace-nowrap">Decision</th>
                  <th className="py-3 px-4 font-label-md text-label-md text-secondary whitespace-nowrap">Reason</th>
                  <th className="py-3 px-4 font-label-md text-label-md text-secondary whitespace-nowrap">Retry Plan</th>
                </tr>
              </thead>
              <tbody className="font-body-sm text-body-sm divide-y divide-outline-variant/20">
                {filteredDecisions.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="py-8 px-4 text-center text-on-surface-variant">
                      No backend recovery decisions match this view.
                    </td>
                  </tr>
                ) : (
                  filteredDecisions.map((item) => (
                    <tr 
                      key={item.id} 
                      onClick={() => setSelectedId(item.id)}
                      className={`hover:bg-surface-container-low transition-colors cursor-pointer ${
                        selectedId === item.id ? 'bg-primary-fixed/30 hover:bg-primary-fixed/40 font-semibold' : ''
                      }`}
                    >
                      <td className="py-4 px-4 font-code text-code text-on-surface">{item.id}</td>
                      <td className="py-4 px-4">
                        <div className="flex items-center gap-2">
                          <span className={`font-medium ${item.probability > 50 ? 'text-primary' : 'text-on-tertiary-fixed-variant'}`}>
                            {item.probability}%
                          </span>
                          <div className="w-16 h-1.5 bg-surface-variant rounded-full overflow-hidden">
                            <div 
                              className={`h-full rounded-full ${item.probability > 50 ? 'bg-primary' : 'bg-tertiary'}`} 
                              style={{ width: `${item.probability}%` }}
                            ></div>
                          </div>
                        </div>
                      </td>
                      <td className="py-4 px-4">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-[11px] font-bold ${item.decisionColor}`}>
                          {item.decision}
                        </span>
                      </td>
                      <td className="py-4 px-4 text-on-surface-variant truncate max-w-[150px]">{item.reason}</td>
                      <td className="py-4 px-4 text-secondary">{item.retryPlan}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Right Side Details Drawer */}
        {activeItem && (
          <aside className="w-full lg:w-96 shrink-0 bg-surface-container-lowest rounded-xl border border-outline-variant/40 shadow-level2 flex flex-col overflow-y-auto z-20">
            {/* Drawer Header */}
            <div className="p-4 border-b border-outline-variant/40 flex justify-between items-center bg-surface-container-low sticky top-0 z-10">
              <div>
                <h3 className="font-title-lg text-title-lg text-on-surface">{activeItem.id}</h3>
                <span className="font-body-sm text-body-sm text-secondary">Details &amp; Insight</span>
              </div>
              <span className="material-symbols-outlined text-[20px] text-outline-variant">psychology</span>
            </div>
            
            <div className="p-4 flex flex-col gap-stack-md flex-1">
              {/* AI Explanation Card */}
              <div className="bg-gradient-to-br from-[#f9f0ff] to-white border border-[#e0caff] shadow-[0_0_15px_rgba(224,202,255,0.4)_inset] rounded-lg p-4 relative overflow-hidden">
                <div className="absolute -right-4 -top-4 text-primary/10">
                  <span className="material-symbols-outlined text-6xl">auto_awesome</span>
                </div>
                <div className="flex items-center gap-2 mb-2 relative z-10">
                  <span className="material-symbols-outlined text-[#8a2be2] text-[18px] fill">auto_awesome</span>
                  <h4 className="font-label-md text-label-md text-[#6b21a8] font-bold">AI Strategy Reasoning</h4>
                </div>
                <p className="font-body-sm text-body-sm text-on-surface-variant relative z-10 leading-relaxed">
                  "{activeItem.reasoning}"
                </p>
              </div>

              {/* Customer Profile & Payment History Grid */}
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-surface rounded-lg border border-outline-variant/30 p-3">
                  <h4 className="font-label-md text-label-md text-secondary mb-1">Customer Profile</h4>
                  <div className="font-title-md text-title-md text-on-surface truncate">{activeItem.customerName}</div>
                  <div className="font-body-sm text-body-sm text-on-surface-variant mt-0.5">{activeItem.customerTier}</div>
                  <div className="font-code text-[10px] text-secondary mt-1 truncate">{activeItem.customerId}</div>
                </div>
                <div className="bg-surface rounded-lg border border-outline-variant/30 p-3">
                  <h4 className="font-label-md text-label-md text-secondary mb-1">Payment History</h4>
                  <div className="font-title-md text-title-md text-on-surface">{activeItem.successRate}% Success</div>
                  <div className="font-body-sm text-body-sm text-on-surface-variant mt-0.5">Avg: {activeItem.avgVolume}</div>
                  <div className="flex gap-1 mt-2">
                    {activeItem.historyDots.map((dotClass, i) => (
                      <div key={i} className={`w-2 h-2 rounded-full ${dotClass}`}></div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Probability Breakdown */}
              <div className="bg-surface rounded-lg border border-outline-variant/30 p-4">
                <h4 className="font-label-md text-label-md text-secondary mb-3 uppercase tracking-wider">Probability Breakdown</h4>
                <div className="flex flex-col gap-2 font-code text-body-sm">
                  <div className="flex justify-between items-center text-on-surface-variant">
                    <span>Base Score</span>
                    <span>{activeItem.breakdown.base}%</span>
                  </div>
                  <div className="flex justify-between items-center text-green-600 font-semibold">
                    <span>Historical Successes</span>
                    <span>+{activeItem.breakdown.history}%</span>
                  </div>
                  <div className={`flex justify-between items-center ${activeItem.breakdown.penalty < 0 ? 'text-error font-semibold' : 'text-on-surface-variant'}`}>
                    <span>Negative Factors</span>
                    <span>{activeItem.breakdown.penalty}%</span>
                  </div>
                  <div className="h-px w-full bg-outline-variant/30 my-1"></div>
                  <div className="flex justify-between items-center font-bold text-on-surface text-title-md">
                    <span>Final Probability</span>
                    <span className="text-primary">{activeItem.probability}%</span>
                  </div>
                </div>
              </div>

              {/* Retry Strategy */}
              <div className="bg-surface rounded-lg border border-outline-variant/30 p-4">
                <h4 className="font-label-md text-label-md text-secondary mb-2 uppercase tracking-wider">Retry Strategy</h4>
                <div className="flex items-start gap-3">
                  <div className="p-2 bg-secondary-fixed rounded text-on-secondary-fixed mt-1">
                    <span className="material-symbols-outlined text-[16px]">schedule</span>
                  </div>
                  <div>
                    <p className="font-title-md text-title-md text-on-surface">Next Attempt: {activeItem.nextAttempt}</p>
                    <p className="font-body-sm text-body-sm text-on-surface-variant mt-1">{activeItem.attemptDetails}</p>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="mt-auto pt-4 flex gap-2">
                <button 
                  onClick={() => handleOverride(activeItem.id)}
                  className="flex-1 py-2 bg-surface hover:bg-surface-container border border-outline-variant/50 rounded-lg font-title-md text-body-md text-on-surface transition-colors"
                >
                  Override
                </button>
                <button 
                  onClick={() => handleConfirmPlan(activeItem.id)}
                  className="flex-1 py-2 bg-primary hover:bg-on-primary-fixed-variant rounded-lg font-title-md text-body-md text-on-primary shadow-sm transition-colors"
                >
                  Confirm AI Plan
                </button>
              </div>
            </div>
          </aside>
        )}
      </div>
    </div>
  );
}
